export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const GET_SPOTIFY_USER_DATA = "GET_SPOTIFY_USER_DATA";
export const GET_SPOTIFY_USER_DATA_SAGA = "GET_SPOTIFY_USER_DATA_SAGA";

export const GET_SPOTIFY_PLAYLISTS = "GET_SPOTIFY_USER_PLAYLISTS";
export const GET_SPOTIFY_PLAYLISTS_SAGA = "GET_SPOTIFY_USER_PLAYLISTS_SAGA";

export const GET_SPOTIFY_TRACKS = "GET_SPOTIFY_TRACKS";
export const GET_SPOTIFY_TRACKS_SAGA = "GET_SPOTIFY_TRACKS_SAGA";
